// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "password": "john",
    "confPassword": "john",
    "role": "user"
}
###
// get All Users
GET http://localhost:5000/users
###
// get single user
GET http://localhost:5000/users/9eeb726e-eae7-47ce-9a25-cf6e308032a4
###
// Update a user
PUT http://localhost:5000/users/513a25ac-cf91-4210-8fcb-26e0415adf56
Content-Type: application/json

{
    "name": "John Doe di update",
    "email": "john@gmail.com",
    "role": "user"
}
###
// Delete a user
DELETE  http://localhost:5000/users/513a25ac-cf91-4210-8fcb-26e0415adf56
###
// Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "john"
}

###
// ME / Get user login
GET http://localhost:5000/me
###
// Logout
POST http://localhost:5000/logout
###
// Get all product
GET http://localhost:5000/products
###
// Add product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 3",
    "price": 8534
}
###
// Get product by id
GET http://localhost:5000/products/193bea81-1ca5-4fbb-96bf-af5e827f3019
###
// Add product
PUT http://localhost:5000/products/e4d96444-37fb-4eb5-b04e-5cb348fa1d8e
Content-Type: application/json

{
    "name": "Product 1 Update",
    "price": 8534
}
###
// delete product by id
DELETE http://localhost:5000/products/193bea81-1ca5-4fbb-96bf-af5e827f3019